name: widget_preview_scaffold
description: Scaffolding for Flutter Widget Previews

environment:
  sdk: ^3.10.0-0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  dtd: any
  file: any
  google_fonts: any
  json_rpc_2: any
  path: any
  stack_trace: any
  url_launcher: any
  web: any
  webview_flutter: any

dev_dependencies:
  flutter_tools:
    path: ../../../packages/flutter_tools/
  test: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

# PUBSPEC CHECKSUM: 7554df
